# **Part A: Load the data using pymongo_Running in Jupyter Notebook**

In [1]:
pip install "pymongo[srv]"

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pymongo

Note: you may need to restart the kernel to use updated packages.


In [3]:
from pymongo import MongoClient
import pymongo
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None

**Create a function to connect MongoDB Atlas,load the jsonfile**

In [4]:
def get_database():
 
    # CONNECTION_STRING = 'mongodb+srv://zy_mongodb:mongodb123@cluster1.k9igo.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
    # client = MongoClient(CONNECTION_STRING)
    # return client['AirlineReview']


    CONNECTION_STRING = 'mongodb+srv://rkatta:rkatta@cluster0.oa2hx.mongodb.net/myFirstDatabase'
    client = MongoClient(CONNECTION_STRING)
    return client['airline']

In [5]:
# # Get the database 
# dbname = get_database()

# # get the collection from the database
# collection_name = dbname['Review']

# Get the database 
dbname = get_database()

# get the collection from the database
collection_name = dbname['airline_reviews']

In [6]:
# convert the dictionary objects to dataframe
df = pd.DataFrame(collection_name.find())
print(df)

                            _id   authorcountry  rating_valuemoney  \
0      58994af99bf56223b02ab85d           Italy                4.0   
1      58994af99bf56223b02ab862       Australia                1.0   
2      58994af79bf56223b02ab85b          Israel                5.0   
3      58994af99bf56223b02ab861   United States                3.0   
4      58994af99bf56223b02ab85c          Canada                4.0   
...                         ...             ...                ...   
41391  58994b179bf56223b02b59de       Australia                5.0   
41392  58994b179bf56223b02b59d5           Egypt                2.0   
41393  58994b179bf56223b02b5a0e  United Kingdom                NaN   
41394  58994b179bf56223b02b5a0b  United Kingdom                NaN   
41395  58994b179bf56223b02b59db           China                5.0   

       recommended                          airlinename   travellertype  \
0                1                   singapore-airlines             NaN   
1        

# **Export to CSV file as data source for Project Part C (Neo4j)**

In [7]:
df_neo4j=df[['airlinename','rating_overall','authorname']]

In [8]:
df_neo4j.rename({"rating_overall":"ratingoverall"},axis=1, inplace=True)
df_neo4j.head()

airlinename  ratingoverall        authorname
0                   singapore-airlines            8.0          A Abbado
1                       etihad-airways            2.0           A Adams
2                el-al-israel-airlines            9.0   Moam Ben-Shalom
3                         thai-airways            4.0          A Acosta
4  pia-pakistan-international-airlines            8.0           A Aamir

**Check the missing value**

In [9]:
df_neo4j.isna().apply(pd.value_counts)

airlinename  ratingoverall  authorname
False      41396.0          36861       41367
True           NaN           4535          29

In [10]:
df_neo4j.isnull().sum()

airlinename         0
ratingoverall    4535
authorname         29
dtype: int64

**Replace missing value in column"rating_overall" with mean**

In [11]:
df_neo4j['ratingoverall'] = df_neo4j['ratingoverall'].fillna(df_neo4j['ratingoverall'].mean())

**Replace missing value in column"authorname" with "unknown"**

In [12]:
df_neo4j["authorname"]=df_neo4j["authorname"].fillna("unknown")

In [13]:
df_neo4j.isnull().sum()

airlinename      0
ratingoverall    0
authorname       0
dtype: int64

In [14]:
df_neo4j.shape

(41396, 3)

In [15]:
df_neo4j.to_csv("Airline_Review.csv")

# **Export to a subset only for Project Part B**

In [16]:
df=df[['reviewcontent','recommended']]

In [17]:
df.to_csv("airline_df.csv",index = False, header=True )

In [18]:
df.shape

(41396, 2)

In [19]:
df.head()

reviewcontent  recommended
0  SQ947 and SQ378 Aug 19 2014. DPS-SIN and SIN-M...            1
1  Arrived early to check in, get good seats and ...            0
2  Flight was half-full. I had the whole row to m...            1
3  BKK-FRA A340. Not what I expected left disappo...            0
4  We have travelled to Pakistan many times on PI...            1

In [20]:
df.recommended.value_counts()

1    22098
0    19298
Name: recommended, dtype: int64

In [21]:
round(df.recommended.value_counts()/len(df)*100,1)

1    53.4
0    46.6
Name: recommended, dtype: float64

# **Part B. Retrieve customer reviews and recommendation from the database, and develop sentiment analysis of reviews**

In [22]:
import numpy as np 
import pandas as pd 

from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
import re

**Import the CSV file which is subset of AirlineReview.json"**

In [23]:
url = 'https://drive.google.com/file/d/1LqrTweFurjDLT7JcHz40YesD1kUeTkMy/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
df = pd.read_csv(path)

In [24]:
df.recommended.value_counts()

1    22098
0    19298
Name: recommended, dtype: int64

In [25]:
round(df.recommended.value_counts()/len(df)*100,1)

1    53.4
0    46.6
Name: recommended, dtype: float64

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41396 entries, 0 to 41395
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   reviewcontent  41396 non-null  object
 1   recommended    41396 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 646.9+ KB


In [27]:
#df["recommended"].replace({1: "positive", 0: "negative"}, inplace=True)
df = df.rename(columns={"recommended": "sentiment"})
df

reviewcontent  sentiment
0      LAX-NRT 777-300ER. FA's stop to pick up every ...          1
1      Flight was half-full. I had the whole row to m...          1
2      We have travelled to Pakistan many times on PI...          1
3      BKK-FRA A340. Not what I expected left disappo...          0
4      4/10/2015 FRA-LAX LH 456. Lufthansa from FRA t...          0
...                                                  ...        ...
41391  KUL-PUS-KUL. Both flights on time despite weat...          1
41392  I was impressed with LUXAIR. My flights were o...          0
41393  Luxembourg - London City return. On a route wh...          0
41394  How come that every time I call Luxair Informa...          0
41395  Flew domestic route Kota Kinabalu - Kuala Lump...          1

[41396 rows x 2 columns]

**Text Date Processing: remove the punctuation, stopwors,stem the words**

In [28]:
import re
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rajes\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [29]:
corpus=[]

for i in range(0, 41396):
  review = re.sub('[^a-zA-Z]', ' ', df['reviewcontent'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

In [30]:
len(corpus)

41396

**Staging and pre-processing the data**

In [31]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras import regularizers

max_words = 5000
max_len = 200

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(corpus)
sequences = tokenizer.texts_to_sequences(corpus)
review_content_processed = pad_sequences(sequences, maxlen=max_len)
print(review_content_processed)

[[   0    0    0 ...  404 1247  460]
 [   0    0    0 ...    6  101    4]
 [   0    0    0 ...  107   43    6]
 ...
 [   0    0    0 ...  726  262  451]
 [   0    0    0 ...  123  104  953]
 [   0    0    0 ...  766 1150  270]]


In [32]:
len(review_content_processed)

41396

In [33]:
review_content_processed[5]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,  318,    7,   44,  256, 1876,  129,  228, 2928,   18,
        366,  104,  995,  310,  178,    8,  757, 1128,  734, 1997, 1155,
        850,  426, 1115,    8,  178,  481,  228, 2928,    7,   69,  216,
       1011,   10,  228, 1641,  133,   52,   72,   

In [34]:
y = df['sentiment']
X=review_content_processed

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [36]:
from tensorflow.keras import preprocessing
maxlen = 200
X_train = preprocessing.sequence.pad_sequences(X_train, maxlen=maxlen)
X_test = preprocessing.sequence.pad_sequences(X_test, maxlen=maxlen)

# **B.1 RNN-Based Sentiment Classification Model**

In [37]:
import numpy as np
import tensorflow as tf

np.random.seed(42)
tf.random.set_seed(42)

In [38]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Flatten, Dense, Embedding, SpatialDropout1D, Dropout

In [39]:
vocab_size = 8000
model_rnn = Sequential()
model_rnn.add(Embedding(vocab_size, output_dim=32))
model_rnn.add(SpatialDropout1D(0.4))
model_rnn.add(SimpleRNN(32))
model_rnn.add(Dropout(0.4))
model_rnn.add(Dense(1, activation='sigmoid'))
model_rnn.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model_rnn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          256000    
                                                                 
 spatial_dropout1d (SpatialD  (None, None, 32)         0         
 ropout1D)                                                       
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                2080      
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 258,113
Trainable params: 258,113
Non-trainable params: 0
__________________________________________________

In [40]:
history_rnn = model_rnn.fit(X_train, y_train, batch_size=128, validation_split=0.2, epochs = 10)

Epoch 1/10
207/207 [==============================] - 16s 65ms/step - loss: 0.4751 - accuracy: 0.7762 - val_loss: 0.3604 - val_accuracy: 0.8537
Epoch 2/10
207/207 [==============================] - 13s 61ms/step - loss: 0.3388 - accuracy: 0.8682 - val_loss: 0.3616 - val_accuracy: 0.8575
Epoch 3/10
207/207 [==============================] - 14s 66ms/step - loss: 0.3062 - accuracy: 0.8834 - val_loss: 0.3310 - val_accuracy: 0.8705
Epoch 4/10
207/207 [==============================] - 13s 64ms/step - loss: 0.2920 - accuracy: 0.8906 - val_loss: 0.3255 - val_accuracy: 0.8735
Epoch 5/10
207/207 [==============================] - 14s 66ms/step - loss: 0.2793 - accuracy: 0.8949 - val_loss: 0.3466 - val_accuracy: 0.8705
Epoch 6/10
207/207 [==============================] - 13s 65ms/step - loss: 0.2667 - accuracy: 0.9008 - val_loss: 0.3327 - val_accuracy: 0.8753
Epoch 7/10
207/207 [==============================] - 13s 65ms/step - loss: 0.2508 - accuracy: 0.9090 - val_loss: 0.3295 - val_accuracy:

In [41]:
#y_test_pred = model_rnn.predict_classes(X_test)
y_test_pred = (model_rnn.predict(X_test) > 0.5).astype("int32")
y_test_pred

array([[1],
       [0],
       [1],
       ...,
       [1],
       [0],
       [1]])

In [42]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_test_pred))

0.8617149758454107


# **B.2 LSTM-Based Sentiment Classification Model**

In [43]:
from tensorflow.keras.layers import LSTM

In [44]:
model_lstm = Sequential()
model_lstm.add(Embedding(vocab_size, output_dim=32))
model_lstm.add(SpatialDropout1D(0.4))
model_lstm.add(LSTM(32))
model_lstm.add(Dropout(0.4))
model_lstm.add(Dense(1, activation='sigmoid'))

model_lstm.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model_lstm.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 32)          256000    
                                                                 
 spatial_dropout1d_1 (Spatia  (None, None, 32)         0         
 lDropout1D)                                                     
                                                                 
 lstm (LSTM)                 (None, 32)                8320      
                                                                 
 dropout_1 (Dropout)         (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 264,353
Trainable params: 264,353
Non-trainable params: 0
________________________________________________

In [45]:
history_lstm = model_lstm.fit(X_train, y_train, batch_size=128, validation_split=0.2, epochs=5)

Epoch 1/5
207/207 [==============================] - 38s 166ms/step - loss: 0.4440 - accuracy: 0.8011 - val_loss: 0.3333 - val_accuracy: 0.8688
Epoch 2/5
207/207 [==============================] - 34s 165ms/step - loss: 0.3053 - accuracy: 0.8862 - val_loss: 0.3232 - val_accuracy: 0.8741
Epoch 3/5
207/207 [==============================] - 33s 161ms/step - loss: 0.2835 - accuracy: 0.8946 - val_loss: 0.3132 - val_accuracy: 0.8771
Epoch 4/5
207/207 [==============================] - 33s 161ms/step - loss: 0.2697 - accuracy: 0.9004 - val_loss: 0.3156 - val_accuracy: 0.8736
Epoch 5/5
207/207 [==============================] - 33s 158ms/step - loss: 0.2633 - accuracy: 0.9034 - val_loss: 0.3196 - val_accuracy: 0.8758


In [46]:
#y_test_pred = model_lstm.predict_classes(X_test)
y_test_pred = (model_lstm.predict(X_test) > 0.5).astype("int32")
y_test_pred

array([[1],
       [0],
       [1],
       ...,
       [1],
       [0],
       [1]])

In [47]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_test_pred))

0.8763285024154589


B.3 GRU-Based Sentiment Classification Model

In [48]:
from tensorflow.keras.layers import GRU

In [49]:
model_gru = Sequential()
model_gru.add(Embedding(vocab_size, output_dim=32))
model_gru.add(SpatialDropout1D(0.4))
model_gru.add(GRU(32))
model_gru.add(Dropout(0.4))
model_gru.add(Dense(1, activation='sigmoid'))

model_gru.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model_gru.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, None, 32)          256000    
                                                                 
 spatial_dropout1d_2 (Spatia  (None, None, 32)         0         
 lDropout1D)                                                     
                                                                 
 gru (GRU)                   (None, 32)                6336      
                                                                 
 dropout_2 (Dropout)         (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 262,369
Trainable params: 262,369
Non-trainable params: 0
________________________________________________

In [50]:
history_gru = model_gru.fit(X_train, y_train, batch_size=128, validation_split=0.2, epochs=5)

Epoch 1/5
207/207 [==============================] - 35s 155ms/step - loss: 0.4745 - accuracy: 0.7698 - val_loss: 0.3423 - val_accuracy: 0.8604
Epoch 2/5
207/207 [==============================] - 31s 152ms/step - loss: 0.3213 - accuracy: 0.8715 - val_loss: 0.3326 - val_accuracy: 0.8667
Epoch 3/5
207/207 [==============================] - 31s 152ms/step - loss: 0.2918 - accuracy: 0.8891 - val_loss: 0.3167 - val_accuracy: 0.8756
Epoch 4/5
207/207 [==============================] - 33s 160ms/step - loss: 0.2725 - accuracy: 0.8977 - val_loss: 0.3105 - val_accuracy: 0.8747
Epoch 5/5
207/207 [==============================] - 33s 161ms/step - loss: 0.2658 - accuracy: 0.9011 - val_loss: 0.3209 - val_accuracy: 0.8742


In [51]:
#y_test_pred = model_lstm.predict_classes(X_test)
y_test_pred = (model_gru.predict(X_test) > 0.5).astype("int32")
y_test_pred

array([[1],
       [0],
       [1],
       ...,
       [1],
       [0],
       [1]])

In [52]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_test_pred))

0.8733091787439613


## Part C. Construct a rating network between authors and the airline companies that they rated. Such rating network captures who rated which airline companies.

##### This section only doesn't work in Google colab as it cannot connect to local host of Neo4j desktop, the csv file Airline_reviews is used to create the network. 

In [53]:
pip install neo4j


Note: you may need to restart the kernel to use updated packages.


In [54]:
from neo4j import __version__ as neo4j_version, GraphDatabase
print(neo4j_version)

4.4.1


In [55]:
from neo4j import GraphDatabase
class Neo4jConnection:
    
    def __init__(self, uri, user, pwd):
        self.__uri = uri
        self.__user = user
        self.__pwd = pwd
        self.__driver = None
        try:
            self.__driver = GraphDatabase.driver(self.__uri, auth=(self.__user, self.__pwd))
        except Exception as e:
            print("Failed to create the driver:", e)
        
    def close(self):
        if self.__driver is not None:
            self.__driver.close()
        
    def query(self, query, db=None):
        assert self.__driver is not None, "Driver not initialized!"
        session = None
        response = None
        try: 
            session = self.__driver.session(database=db) if db is not None else self.__driver.session() 
            response = list(session.run(query))
        except Exception as e:
            print("Query failed:", e)
        finally: 
            if session is not None:
                session.close()
        return response

In [56]:
conn = Neo4jConnection(uri="bolt://127.0.0.1:7687", user="rkatta", pwd="rkatta")

#### Find top 5 airlines with highest number of reviewers

In [57]:
query_string = '''
Match (a:airline)-[r:rated]-(author) return a.name,count(r) as NumberOfReviews order by NumberOfReviews desc limit 5;
'''
conn.query(query_string, db='ratingairline')

[<Record a.name='spirit-airlines' NumberOfReviews=984>,
 <Record a.name='british-airways' NumberOfReviews=838>,
 <Record a.name='united-airlines' NumberOfReviews=814>,
 <Record a.name='jet-airways' NumberOfReviews=712>,
 <Record a.name='air-canada-rouge' NumberOfReviews=706>]

####  Find top 5 authors with highest number of reviews

In [58]:
query_string = '''
Match (airline)-[r:rated]-(a:author) return a.name,count(r) as ReviewsGiven order by ReviewsGiven desc limit 5;
'''
conn.query(query_string, db='ratingairline')

[<Record a.name='Tercon Bojan' ReviewsGiven=44>,
 <Record a.name='Roger Stone' ReviewsGiven=41>,
 <Record a.name='Steven Cao' ReviewsGiven=39>,
 <Record a.name='D Graubard' ReviewsGiven=34>,
 <Record a.name='Anders Pedersen' ReviewsGiven=34>]

####  List of airlines reviewed by A Adrian

In [59]:
query_string = '''
Match (a:airline)<-[r:rated]-(au:author) where au.name = 'A Adrian' return a.name;
'''
conn.query(query_string, db='ratingairline')

[<Record a.name='dniproavia'>]